# Generated by Django 5.0.6 on 2024-05-23 21:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('investment_type', models.CharField(blank=True, max_length=500, null=True)),
                ('btc_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('btc_hash_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('added_to_balance', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
            },
        ),
        migrations.CreateModel(
            name='Crypto_Withdrawal_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('crypto', models.CharField(blank=True, max_length=300, null=True)),
                ('btc_address', models.CharField(blank=True, max_length=5000, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20, null=True)),
                ('remove_from_balance', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
            },
        ),
        migrations.CreateModel(
            name='Referral_Withdrawal_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('crypto', models.CharField(blank=True, max_length=300, null=True)),
                ('btc_address', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20, null=True)),
                ('remove_from_balance', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
