# Generated by Django 5.0.6 on 2024-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('Payment Gateway', 'Payment Gateway'), ('Payment Account', 'Payment Account')], default='Payment Gateway', max_length=500, null=True),
        ),
    ]
