# Generated by Django 5.0.6 on 2024-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_crypto_wallet_type_crypto_detail_alter_crypto_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceCrypto',
            fields=[
            ],
            options={
                'verbose_name': 'Account Wallet Investment',
                'verbose_name_plural': 'Account Wallet Investments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.crypto',),
        ),
        migrations.CreateModel(
            name='PaymentGatewayCrypto',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Investment',
                'verbose_name_plural': 'Deposit Investments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.crypto',),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Investment', 'Investment')], default='Deposit', max_length=500, null=True),
        ),
    ]
