# Generated by Django 5.0.6 on 2024-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_accountbalancecrypto_paymentgatewaycrypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Referral_Withdrawal_Request',
        ),
    ]
