# Generated by Django 5.0.6 on 2024-08-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_delete_accountbalancecrypto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_withdrawal_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True),
        ),
    ]
