# Generated by Django 5.0.6 on 2024-08-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_transaction_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='percent',
        ),
    ]
