# Generated by Django 5.0.6 on 2024-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_withdrawal_request',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
