# Generated by Django 5.0.6 on 2024-08-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_crypto_withdrawal_request_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_withdrawal_request',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
