# Generated by Django 5.0.6 on 2024-08-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_crypto_withdrawal_request_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_withdrawal_request',
            name='Wallet_Type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
