# Generated by Django 3.2 on 2024-09-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='interest_wallet',
            new_name='balance',
        ),
    ]
