# Generated by Django 3.2 on 2024-09-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_interest_wallet_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='crypto_balance',
        ),
    ]
